= CustomAsioStreams
raldone01 <https://github.com/raldone01/[@raldone01]>
// settings:
:idprefix:
:idseparator: -
ifndef::env-github[:icons: font]
ifdef::env-github[]
:status:
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]
// Variables:
// URLs:
:url-project: https://github.com/raldone01/CustomAsioAsyncStreams
// images:
// :image-url-screenshot: https://cdn.jsdelivr.net/gh/asciidoctor/asciidoctor/screenshot.png

{url-project}[CustomAsioStreams] is a small example showing how to create custom streams that integrate nicely into the asio library.

== Building

If you want to build this project you should define the `CPM_SOURCE_CACHE` env variable and point it to a folder to avoid downloading the dependencies multiple times. Boost and fmt will be installed to that directory.

== Targets

=== CoroContextSwitching

Shows off how you can easily switch between executors (threads/strands/execution_contexts) using `co_await` and `post`.

Also shows how to make the `int main()` into a `asio::awaitable<int> mainCo()` coroutine.
This is comparable to how you would make `node.js` asynchronous.

=== AsyncCalls

Shows off how to use different completion tokens to call
various async function signatures.
Shows how to handle exceptions and error_codes properly.

=== SimpleAsyncService

Shows off how to write a basic service with its own executor and its own async functions. The service implements two async functions which do the same thing. One depends on coroutines to be available. The other can be implemented in cpp17.

It should be used when using an AsyncStream is overkill and all data is available instantly.

=== WorkGuards

Shows off different kinds of work guards and an example use case.

=== CustomAsioReadStream

This is the main target of the project.
It shows off how to create a custom AsyncReadStream and how to interact with it.
I have added plenty of comments to try and explain why I did what I did.

=== CustomAsioWriteStream

Take a look at CustomAsioReadStreams first because it is more detailed.

This target shows off how to create a custom AsyncWriteStream and how to interact with it.
I have added a few comments to try and explain why I did what I did.

=== Fluff - CoroOutcomeReturn

Shows how to return a `boost::outcome` from an `asio::awaitable`.

=== Fluff - IteratorConcepts

Shows how to use the new c++20 iterator concepts defined in the <iterator> header.

=== TODO
* CustomStreams: Check if get_associated_executor can be used in the custom streams example
* CustomStreams: use bind_executor in every post,defer,dispatch statement
* Everywhere: Move completion handler before invoking
* Revisit work_guards - Create a proper work guard example
* NewEx: Show how to use captured_self to control lifetimes.
* NewEx: Show how to use and implement cancellation in custom async functions.
* NewEx: Show how to store completion handlers in a vector
* NewEx: Show how the system executor is dangerous and how to exit it cleanly (use query)

=== Questions
* When is the first argument of `post, dispatch, defer` ever useful?
 It's just a BAD FALLBACK when no bound executor is found. And if one is found it first post empty work to the FALLBACK and the dispatches from there to the associated executor. When is that EVER useful? post.hpp:63 https://www.boost.org/doc/libs/1_79_0/doc/html/boost_asio/reference/get_associated_executor/overload3.html
* Additionally, the naming of the asio parameters is not really intuitive, and it's lacking parameter descriptions of the overloads of very popular functions `post, dispatch, defer`.
* Biggest issue for beginner is the lack of examples and documentation.
  Even parameter names or simple sentences explaining one possible use case would be very helpful. Especially parameter descriptions. Also maybe note what the different overloads are for.

=== About

This repository is a collection of useful snippets I wrote to help me understand asio better.
Thanks sehe for helping me out over on stackoverflow.
