= CustomAsioStreams
raldone01 <https://github.com/raldone01/[@raldone01]>
// settings:
:idprefix:
:idseparator: -
ifndef::env-github[:icons: font]
ifdef::env-github[]
:status:
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]
// Variables:
// URLs:
:url-project: https://github.com/raldone01/CustomAsioAsyncStreams
// images:
// :image-url-screenshot: https://cdn.jsdelivr.net/gh/asciidoctor/asciidoctor/screenshot.png

{url-project}[CustomAsioStreams] is a small example showing how to create custom streams that integrate nicely into the asio library.

== Targets

=== CustomAsioReadStreams

This is the main target of the project.
It shows off how to create a custom AsyncReadStream and how to interact with it.
I have added plenty of comments to try and explain why I did what I did.

=== CustomAsioWriteStreams

Take a look at <<CustomAsioReadStreams>> first because it is more detailed.

This target shows off how to create a custom AsyncWriteStream and how to interact with it.
I have added a few comments to try and explain why I did what I did.

=== IteratorConcepts

Shows how to use the new c++20 iterator concepts defined in the <iterator> header.

=== WorkGuards

Shows off different kinds of work guards and an example use case.
